C      COLUNA 7 EM DIANTE PARA O CODIGO
       PROGRAM TESTE
       WRITE(*,*) '************************************'
       WRITE(*,*) '*   MAGICFORT RODANDO NO M3 MAX    *'
       WRITE(*,*) '************************************'
       PRINT *, 'DIGITE UM NUMERO:'
       READ(*,*) I
       PRINT *, 'O DOBRO DESTE NUMERO E:', I * 2
       END
C      COLUNA 7 EM DIANTE PARA O CODIGO
       PROGRAM TESTE
       WRITE(*,*) '************************************'
       WRITE(*,*) '*   MAGICFORT RODANDO NO M3 MAX    *'
       WRITE(*,*) '************************************'
       PRINT *, 'DIGITE UM NUMERO:'
       READ(*,*) I
       PRINT *, 'O DOBRO DESTE NUMERO E:', I * 2
       END
