[sdl]
output=surface
windowresolution=1024x768

[autoexec]
@echo off
MOUNT C ~/dosprojs/msfor51
C:
# Configura o acesso aos binários já extraídos
SET PATH=C:\BIN;C:\BINB;%PATH%
SET LIB=C:\LIB
SET INCLUDE=C:\INCLUDE
SET HELPFILES=C:\HELP\*.HLP
echo Microsoft Fortran 5.1 Carregado no M3 Max!
echo Use 'FL arquivo.for' para compilar.
# 4. Limpa a tela e te deixa pronto para programar
CLS

# 3. Comando para evitar que programas antigos travem na rede/arquivos
SET SHARE=1
